backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: gitbush/revolve-coaching # Path to your GitHub repository

# This line should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
media_library:
  name: uploadcare


collections:
  - name: posts
  - identifier_field: name
  - label: Blog post
  - 