backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "/static/img" # Media files will be stored in the repo under "/static/img"

local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    files: 
      - label: "Home Page"
        name: "home page"
        file: "src/site/index.njk"
        fields:
          - {label: "Hero text first line", name: "heroTextFirstLine", widget: string}
          - {label: "Hero text second line", name: "heroTextSecondLine", widget: "string"}
          - {label: "Hero text third line", name: "heroTextThirdLine", widget: "string"}
            # allow_add: false
            # collapsed: false
            
    create: false
    editor:
      preview: false
